baseurl: "/blog"
url: "https://roberteaston.github.io"
title: The Covariant Functor
subtitle: Preserving Arrows since 2021
author: Robert Easton
simple_search: http://google.com/search
description: A Jekyll theme for content-rich sites
name: tufte
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/